### ISSUE TITLE
CMILib version 1.2.3.4 breaks next/back buttons for CMI custom text

### ISSUE THREAD

**Issue by emkirsh** [Zrips/CMILib#10]
Hi! Just wanted to make you aware that the latest version of CMILib, 1.2.3.4, seems to be breaking the Next/Prev buttons on customtexts. Specifically, the next button goes to the previous page and the previous page also goes to the previous page. Interestingly, the issue only appeared on one of our custom texts, which I'll attach, but we temporarily fixed the problem by downgrading CMILib to 1.2.3.3, which leads me to believe it was an issue with CMILib and not our custom text. The version of CMI seemed to be irrelevant as (at the time of writing, the latest) version 9.2.3.6 worked fine paired with CMIL 1.2.3.3 and broke with 1.2.3.4.

[Attached is the customtext that CMIL1.2.3.4 broke.](https://github.com/Zrips/CMILib/files/9449131/help.txt)

Lastly, just wanted to ask if it was intentional that CMIL 1.2.3.4 was never uploaded to spigotmc?

Thanks in advance!
-emkirsh & SurvivalQuest team.

**Comment by mrfloris** [comment]
Hey there,

Apologies in the long wait, we're still on the same CMILib version, but CMI itself has progressed to 9.3.x by now after all these months.

Putting the .txt file on a test server and going through the pagination, it works for me. 

If you still have this as an issue could you please let us know? Hopefully it's been resolved since last August.
