### ISSUE TITLE
` StackOverflowError` on roman number formatting

### ISSUE THREAD

**Issue by skykatik** [Zrips/CMILib#41]
Hello. While using the CMI (9.6.10.6) and CMILib (1.4.5.2) I noticed that when using `net.Zrips.CMILib.Container.CMINumber.toRoman(Integer.MAX_VALUE)` causes `StackOverflowError` on any environment. So, I think this is easy to fix, but can’t create PR now

**Comment by Zrips** [comment]
That code isn't really suitable to convert such huge numbers due to Romans not liking to have letter to represent bigger values, jokes aside, will add hard limit for this to be no more than 3999 as it gets ridiculous looking after that point in any case and not really usable. 
d5025a5ee78a942560d6ea590edaddce9050aca1
